# 生成 streetlight_config.h（WiFi + EMQX + deviceSn）
# 用法:
#   powershell -ExecutionPolicy Bypass -File firmware\scripts\configure-streetlight.ps1 `
#     -WifiSsid "你的WiFi" -WifiPsk "密码" -DeviceSn SN-RM-001

param(
    [Parameter(Mandatory = $true)]
    [string]$WifiSsid,
    [Parameter(Mandatory = $true)]
    [string]$WifiPsk,
    [string]$DeviceSn = 'SN-RM-001',
    [string]$BrokerIp = '',
    [int]$BrokerPort = 1883,
    [int]$LightReportSec = 15,
    [string]$StreetlightDir = ''
)

$ErrorActionPreference = 'Stop'
$root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
if (-not $StreetlightDir) {
    $StreetlightDir = Join-Path $root 'firmware\streetlight'
}

if (-not $BrokerIp) {
    $candidates = Get-NetIPAddress -AddressFamily IPv4 |
        Where-Object {
            $_.IPAddress -notlike '127.*' -and
            $_.IPAddress -notlike '169.254.*' -and
            $_.InterfaceAlias -notmatch 'WSL|Hyper-V|vEthernet|VMware|VirtualBox'
        } |
        Sort-Object -Property @{
            Expression = {
                if ($_.InterfaceAlias -match 'WLAN|Wi-Fi|无线') { 0 }
                elseif ($_.IPAddress -like '192.168.*') { 1 }
                else { 2 }
            }
        }, IPAddress
    $BrokerIp = ($candidates | Select-Object -First 1).IPAddress
    if (-not $BrokerIp) { throw 'Cannot detect LAN IP; pass -BrokerIp explicitly' }
} elseif ($BrokerIp -match '[\u4e00-\u9fff]' -or $BrokerIp -match '热点|IP|你的') {
    throw "BrokerIp looks like a placeholder ($BrokerIp). Use ipconfig WLAN IPv4, or omit -BrokerIp to auto-detect."
}

$dest = Join-Path $StreetlightDir 'streetlight_config.h'
$content = @"
/*
 * Auto-generated by configure-streetlight.ps1
 * deviceSn 须与 Web 设备页一致
 */
#ifndef STREETLIGHT_CONFIG_H
#define STREETLIGHT_CONFIG_H

#define WIFI_SSID           "$WifiSsid"
#define WIFI_PSK            "$WifiPsk"

#define MQTT_BROKER_IP      "$BrokerIp"
#define MQTT_BROKER_PORT    $BrokerPort

#define DEVICE_SN           "$DeviceSn"

#define LIGHT_REPORT_SEC    $LightReportSec

#endif
"@

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($dest, $content, $utf8NoBom)
Write-Host "Wrote $dest"
Write-Host "  WiFi SSID : $WifiSsid"
Write-Host "  MQTT      : ${BrokerIp}:$BrokerPort"
Write-Host "  deviceSn  : $DeviceSn"
